### ISSUE TITLE
Assertion `s1' failed

### ISSUE THREAD

**Issue by p10tyr** [stolk/chiaplotgraph#11]
When a plot is somewhere past stage 3 I think this error shows up and the GUI bombs out.

```
Opened /mnt/c/Users/pkula/.chia/mainnet/plotter/plotter_log_8fcd7656-8e8a-4dae-b16f-dad8172d4d03.txt
tmp dirname: F:\
chiaplotgraph: chiaplotgraph.c:203: analyze_line: Assertion `s1' failed.
Aborted
```

**Comment by stolk** [comment]
Can you pull the latest, and try again please? I put in a fix for this.
```
$ git pull
$ make clean
$ make
```
Thx!

**Comment by p10tyr** [comment]
Yes. Fixes it thanks 🙏

On 5 Jun 2021, at 17:45, Bram Stolk ***@***.***> wrote:

﻿

Can you pull the latest, and try again please? I put in a fix for this.

$ git pull
$ make clean
$ make


Thx!
