### ISSUE TITLE
New plots not pulled in to graph despite using *.log wildcard when running command

### ISSUE THREAD

**Issue by ilovepancakes95** [stolk/chiaplotgraph#8]
I run the program using `./chiaplotgraph ~/plotman_logs/*.log` so it automatically uses all log files in that folder, but once the program is running, although it refreshes to update the graph with logs that existed when command was run, it doesn't start pulling in new logs that get added to that folder, even though I used *.log in the command. Is there a way to run this so I don't need to quit the program and re-run my original command in order to pull in new plots that started by plotman?

**Comment by stolk** [comment]
There is no such functionality. The `*` gets expanded at the moment the program is launched.

Intended use is for log files of chia create commands that are set to create many plots in succession with the `—num` argument.

**Comment by ilovepancakes95** [comment]
Hmm, okay, so that method of running plots keeps everything in 1 log file
instead of a new one for each plot?

I guess I could write a small script that runs your program and then quits
and re-runs it every few minutes in order to pick up new log files.

**Comment by stolk** [comment]
That is correct, you would get larger log files.

to parallel plot, you would run multiple of these, e.g. 3 of them on a 1TB nvme drive, and you just let those run until the hdd is full w plots.

i understand that most people use plotman or something similar, in which case you may get many small log files.

**Comment by ilovepancakes95** [comment]
Ahh okay, I'll probably write a script then to just reload the program every so often so it picks up new files and keeps calculating the average plot time. Continuing to use plotman is helpful, but so is your program. Thanks for the effort on it, by the way.
